/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    'CarteFonctionalité': typeof import('./src/components/CarteFonctionalité.vue')['default']
    CarteUtilisation: typeof import('./src/components/CarteUtilisation.vue')['default']
    PagePrincipale: typeof import('./src/components/PagePrincipale.vue')['default']
    TitreSection: typeof import('./src/components/TitreSection.vue')['default']
  }
}
