/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    'CarteFonctionalité': typeof import('./src/components/CarteFonctionalité.vue')['default']
    'CarteTéléchargement': typeof import('./src/components/CarteTéléchargement.vue')['default']
    CarteUtilisation: typeof import('./src/components/CarteUtilisation.vue')['default']
    IndiceInstallationApple: typeof import('./src/components/IndiceInstallationApple.vue')['default']
    'ItemLangueProgrès': typeof import('./src/components/ItemLangueProgrès.vue')['default']
    MenuLangues: typeof import('./src/components/MenuLangues.vue')['default']
    PagePrincipale: typeof import('./src/components/PagePrincipale.vue')['default']
    'PageTéléchargements': typeof import('./src/components/PageTéléchargements.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TitreSection: typeof import('./src/components/TitreSection.vue')['default']
  }
}
